title: GridStation
description: Draw grids with text.
baseurl: /grid-station
url: https://tyleretters.github.io/grid-station
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
collections_dir: collections