title: GridStation
description: Draw grids with text.
baseurl: /GridStation
url: https://tyleretters.github.io/GridStation
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
include: ['_pages']
collections_dir: collections