title: perfect bootstrap jekyll
description: the perfect bootstrap jekyll starting theme. xoxo northern information.
baseurl: /perfect-bootstrap-jekyll
url: https://tyleretters.github.io/perfect-bootstrap-jekyll
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
collections_dir: collections
collections:
  - examples